# Generated by Django 5.2 on 2025-11-23 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='AISerbestChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konusma_id', models.UUIDField(default=uuid.uuid4, verbose_name="Konuşma ID'si")),
                ('kullanici_mesaji', models.TextField()),
                ('ai_cevabi', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Serbest Chat Kaydı',
                'verbose_name_plural': 'AI Serbest Chat Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CevapKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_icerigi', models.TextField()),
                ('kullanici_cevabi', models.TextField()),
                ('dogru_mu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
            ],
            options={
                'verbose_name': 'Cevap Kaydı',
                'verbose_name_plural': 'Cevap Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='CalismaPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_baslik', models.CharField(max_length=255)),
                ('gorev_aciklama', models.TextField(help_text='Yapay zeka tarafından üretilen detaylı görev açıklaması.')),
                ('gorev_tipi', models.CharField(choices=[('SORU', 'Soru Çözme'), ('OKUMA', 'Okuma'), ('OZET', 'Özet Çıkarma'), ('PROJE', 'Proje/Uygulama'), ('DIGER', 'Diğer')], default='SORU', max_length=5)),
                ('durum', models.CharField(choices=[('YENI', 'Yeni Başladı'), ('DEVAM', 'Devam Ediyor'), ('TAMAM', 'Tamamlandı'), ('ATLA', 'Atlandı')], default='YENI', max_length=5)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
            ],
            options={
                'verbose_name': 'Çalışma Planı Görevi',
                'verbose_name_plural': 'Çalışma Planı Görevleri',
                'ordering': ['durum', 'olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.IntegerField(default=1)),
                ('cozulen_soru_sayisi', models.IntegerField(default=0)),
                ('son_aktiflik', models.DateTimeField(auto_now=True)),
                ('sinif_seviyesi', models.IntegerField(default=5, verbose_name='Sınıf Seviyesi')),
                ('ulkede_egitim', models.CharField(default='Türkiye', max_length=50, verbose_name='Eğitim Aldığı Ülke')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci İlerleme Kaydı',
                'verbose_name_plural': 'Öğrenci İlerleme Kayıtları',
                'unique_together': {('kullanici', 'ders')},
            },
        ),
    ]
