# Generated by Django 5.2 on 2025-11-11 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CevapKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField()),
                ('kullanici_cevabi', models.TextField()),
                ('is_dogru', models.BooleanField(default=False)),
                ('cevap_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_cozulen_soru', models.IntegerField(default=0)),
                ('dogru_cevap_sayisi', models.IntegerField(default=0)),
                ('yanlis_cevap_sayisi', models.IntegerField(default=0)),
                ('toplam_calisma_suresi_dk', models.IntegerField(default=0)),
                ('ai_seviye_skoru', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'ders')},
            },
        ),
    ]
