# Generated by Django 5.2 on 2025-11-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISerbestChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_mesaji', models.TextField()),
                ('ai_cevabi', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Serbest Chat Kaydı',
                'verbose_name_plural': 'AI Serbest Chat Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
