# Generated by Django 5.2 on 2025-11-25 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogrenciilerleme',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='ogrenciilerleme',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='arkadas_kodu',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ArkadaslikIstegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabul_edildi', models.BooleanField(default=False)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_istekler', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_istekler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatOdasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('katilimcilar', models.ManyToManyField(related_name='chat_odalari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdaMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='ogrenme.chatodasi')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.DeleteModel(
            name='CalismaPlani',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='cozulen_soru_sayisi',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='ders',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='seviye',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='sinif_seviyesi',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='son_aktiflik',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='ulkede_egitim',
        ),
    ]
