# Generated by Django 5.2 on 2025-11-18 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenme', '0002_aiserbestchat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cevapkaydi',
            options={'verbose_name': 'Cevap Kaydı', 'verbose_name_plural': 'Cevap Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='ders',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='ogrenciilerleme',
            options={'verbose_name': 'Öğrenci İlerleme Kaydı', 'verbose_name_plural': 'Öğrenci İlerleme Kayıtları'},
        ),
        migrations.RenameField(
            model_name='cevapkaydi',
            old_name='is_dogru',
            new_name='dogru_mu',
        ),
        migrations.RenameField(
            model_name='cevapkaydi',
            old_name='soru_metni',
            new_name='soru_icerigi',
        ),
        migrations.RenameField(
            model_name='cevapkaydi',
            old_name='cevap_tarihi',
            new_name='tarih',
        ),
        migrations.RenameField(
            model_name='ogrenciilerleme',
            old_name='dogru_cevap_sayisi',
            new_name='cozulen_soru_sayisi',
        ),
        migrations.RenameField(
            model_name='ogrenciilerleme',
            old_name='son_guncelleme',
            new_name='son_aktiflik',
        ),
        migrations.RemoveField(
            model_name='ders',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='ai_seviye_skoru',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='toplam_calisma_suresi_dk',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='toplam_cozulen_soru',
        ),
        migrations.RemoveField(
            model_name='ogrenciilerleme',
            name='yanlis_cevap_sayisi',
        ),
        migrations.AddField(
            model_name='ders',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='seviye',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ogrenciilerleme',
            name='kullanici',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CalismaPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_baslik', models.CharField(max_length=255)),
                ('gorev_aciklama', models.TextField(help_text='Yapay zeka tarafından üretilen detaylı görev açıklaması.')),
                ('gorev_tipi', models.CharField(choices=[('SORU', 'Soru Çözme'), ('OKUMA', 'Okuma'), ('OZET', 'Özet Çıkarma'), ('PROJE', 'Proje/Uygulama'), ('DIGER', 'Diğer')], default='SORU', max_length=5)),
                ('durum', models.CharField(choices=[('YENI', 'Yeni Başladı'), ('DEVAM', 'Devam Ediyor'), ('TAMAM', 'Tamamlandı'), ('ATLA', 'Atlandı')], default='YENI', max_length=5)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çalışma Planı Görevi',
                'verbose_name_plural': 'Çalışma Planı Görevleri',
                'ordering': ['durum', 'olusturma_tarihi'],
            },
        ),
    ]
