# Generated by Django 5.2 on 2025-11-26 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenme', '0002_alter_ogrenciilerleme_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogrenciilerleme',
            options={'verbose_name': 'Öğrenci İlerleme Kaydı', 'verbose_name_plural': 'Öğrenci İlerleme Kayıtları'},
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='cozulen_soru_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='ders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ogrenme.ders'),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='kullanici',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='seviye',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='sinif_seviyesi',
            field=models.IntegerField(default=5, verbose_name='Sınıf Seviyesi'),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='son_aktiflik',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ogrenciilerleme',
            name='ulkede_egitim',
            field=models.CharField(default='Türkiye', max_length=50, verbose_name='Eğitim Aldığı Ülke'),
        ),
        migrations.AlterUniqueTogether(
            name='ogrenciilerleme',
            unique_together={('kullanici', 'ders')},
        ),
    ]
